# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 330e2a5a96ae99d7253c066a404557dd4b226322302e95fdf841771465f1f09ac575036c24d8db817b93b0125fef4e4ef5565aabbf5f007ae30f4401e0c5413a

test:
  secret_key_base: effe0376ecf4c91c36b6053d1281147e8a2813b48a35089af03cd5a45515f23aa499b46f550d6daff0b9accd9cdb45fbf4606d72a3d2ba5d64153a9f65130553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
