
User.create(name: 'Jorge', email: 'jorgeperis@gmail.com', password: "123456")
User.create(name: 'Laura', email: 'laura@gmail.com', password: "123456")
User.create(name: 'Juan Vicente', email: 'juanvi@gmail.com', password: "123456")
User.create(name: 'Maria Dolores', email: 'madolo@gmail.com', password: "123456")
User.create(name: 'Nera', email: 'nera@gmail.com', password: "123456")
User.create(name: 'Monica', email: 'monica@gmail.com', password: "123456")
User.create(name: 'Javi', email: 'javi@gmail.com', password: "123456")
User.create(name: 'Mireia', email: 'mireia@gmail.com', password: "123456")
User.create(name: 'Dolores', email: 'dolores@gmail.com', password: "123456")
User.create(name: 'Andres', email: 'andres@gmail.com', password: "123456")
User.create(name: 'Elena', email: 'elena@gmail.com', password: "123456")

nera = User.find_by(name: 'Nera')
elena = User.find_by(name: 'Elena')
javi = User.find_by(name: 'Javi')

Product.create(title: 'Rascador', description: 'Rascador de gatos', deadline: "2016-07-06 20:09:59", user: nera, minimun_bid: 20)
Product.create(title: 'Television', description: 'TV 40"', deadline: "2016-07-09 10:09:59", user: elena, minimun_bid: 100)
Product.create(title: 'Moto', description: '125cc', deadline: "2016-07-09 09:09:59", user: javi, minimun_bid: 200)

rascador = Product.find_by(title: 'Rascador')
television = Product.find_by(title: 'Television')
moto = Product.find_by(title: 'Moto')

Bid.create(amount: 30, user: javi, product: rascador)
Bid.create(amount: 40, user: javi, product: rascador)
Bid.create(amount: 101, user: nera, product: television)
Bid.create(amount: 50, user: elena, product: rascador)
Bid.create(amount: 210, user: nera, product: moto)
Bid.create(amount: 220, user: elena, product: moto)
