# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7e402131b21c4f00b279324d488abc2904e097f3f41f0b26ad34f32d8448f21fd7cc6f15420e34500b74e19e317fc7fbf2697177f6c0f4e97a394258b3935b0

test:
  secret_key_base: 32f9526c21c2d7e9df84151656197708f67843c264146edc6e8c69600db8275a51f3f315c342b65f47379c256a1d90b0479595fbf310c98accfcad5038d28029

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
